package net.ausiasmarch.pojo;
// Generated 13-feb-2013 11:27:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

    public Genero() {
    }

	
    public Genero(String nombre) {
        this.nombre = nombre;
    }
    public Genero(String nombre, Set<Pelicula> peliculas) {
       this.nombre = nombre;
       this.peliculas = peliculas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Pelicula> getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set<Pelicula> peliculas) {
        this.peliculas = peliculas;
    }




}


