package net.ausiasmarch.pojo;
// Generated 24-feb-2013 19:42:37 by Hibernate Tools 3.2.1.GA



/**
 * Interpreta generated by hbm2java
 */
public class Interpreta  implements java.io.Serializable {


     private Integer id;
     private Actor actor;
     private Pelicula pelicula;

    public Interpreta() {
    }

    public Interpreta(Actor actor, Pelicula pelicula) {
       this.actor = actor;
       this.pelicula = pelicula;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Actor getActor() {
        return this.actor;
    }
    
    public void setActor(Actor actor) {
        this.actor = actor;
    }
    public Pelicula getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }




}


