package net.ausiasmarch.pojo;
// Generated 13-feb-2013 11:27:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private Integer id;
     private Director director;
     private Genero genero;
     private String titulo;
     private String vo;
     private String descripcion;
     private Integer calificacion;
     private int duracion;
     private Date fecha;
     private Set<Actor> actores = new HashSet<Actor>(0);

    public Pelicula() {
    }

	
    public Pelicula(Director director, Genero genero, String titulo, int duracion, Date fecha) {
        this.director = director;
        this.genero = genero;
        this.titulo = titulo;
        this.duracion = duracion;
        this.fecha = fecha;
    }
    public Pelicula(Director director, Genero genero, String titulo, String vo, String descripcion, Integer calificacion, int duracion, Date fecha, Set<Actor> actores) {
       this.director = director;
       this.genero = genero;
       this.titulo = titulo;
       this.vo = vo;
       this.descripcion = descripcion;
       this.calificacion = calificacion;
       this.duracion = duracion;
       this.fecha = fecha;
       this.actores = actores;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Director getDirector() {
        return this.director;
    }
    
    public void setDirector(Director director) {
        this.director = director;
    }
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getVo() {
        return this.vo;
    }
    
    public void setVo(String vo) {
        this.vo = vo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Actor> getActores() {
        return this.actores;
    }
    
    public void setActores(Set<Actor> actores) {
        this.actores = actores;
    }




}


