package net.ausiasmarch.pojo;
// Generated 14-feb-2013 15:47:47 by Hibernate Tools 3.2.1.GA



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable, GenericPojo {


     private Integer id;
     private String login;
     private String password;

    public Usuario() {
    }

    public Usuario(String login, String password) {
       this.login = login;
       this.password = password;
    }
   
    @Override
    public Integer getId() {
        return this.id;
    }
    
    @Override
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


